<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Bertahan</RootNamespace>
    <AssemblyName>Bertahan</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>1.0.1</Version>
    <Product>Bertahan</Product>
    <Company>Subadubin Studios</Company>
    <Authors>Ariana Mischa Fadhila</Authors>
    <Copyright>Subadubin Studios</Copyright>
    <ApplicationIcon>../../packaging/icons/bertahan.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="ThreeNet" Version="0.6.0" />
    <PackageReference Include="ThreeNet.Avalonia" Version="0.6.0" />
    <PackageReference Include="ThreeNet.Native" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../packaging/icons/bertahan-256.png" Link="icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
